workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^do/
      when: always
    - if: $CI_COMMIT_TAG =~ /^v/
      when: always

stages:
  - build
  - test

job 1:
  stage: build
  image: docker:20.10.8
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20.10.8-dind
  before_script:
    - apk --update add docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/ci-cd-demo_php:hot || true
    - docker-compose build
    - docker tag ci-cd-demo_php:latest $CI_REGISTRY_IMAGE/ci-cd-demo_php:$CI_COMMIT_TAG
    - docker tag ci-cd-demo_php:latest $CI_REGISTRY_IMAGE/ci-cd-demo_php:hot
    - docker images
    - docker push $CI_REGISTRY_IMAGE/ci-cd-demo_php:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/ci-cd-demo_php:hot

job 2:
  stage: test
  script: 
    - echo "hello test"